version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::776257865664:user/aws-sam-cli-managed-dev-env-pipeline-r-PipelineUser-x39W71XgWDh5"
permissions_provider = "AWS IAM"

[dev_env.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::776257865664:role/aws-sam-cli-managed-dev-env-p-PipelineExecutionRole-KlqjD9S6NW1f"
cloudformation_execution_role = "arn:aws:iam::776257865664:role/aws-sam-cli-managed-dev-e-CloudFormationExecutionRo-DExaykJfhj7j"
artifacts_bucket = "aws-sam-cli-managed-dev-env-pipel-artifactsbucket-2afo7d2c89kk"
image_repository = ""
region = "us-east-1"

[prod_env.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::776257865664:role/aws-sam-cli-managed-prod-env--PipelineExecutionRole-4fwtWibxFzhz"
cloudformation_execution_role = "arn:aws:iam::776257865664:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-y8fcAoWkl2Ka"
artifacts_bucket = "aws-sam-cli-managed-prod-env-pipe-artifactsbucket-1c1mv57aate5h"
image_repository = ""
region = "us-east-1"
